version: 2.1

jobs:
  go-test:
    docker:
      - image: docker.mirror.hashicorp.services/golang:1.14
    steps:
      - checkout
      - run: go get -u ./...
      - run: go test -v ./...

workflows:
  version: 2
  test-and-build:
    jobs:
      - go-test
